version: 2.1

parameters:
  sfml_dependencies:
    type: string
    default: "libfreetype-dev libx11-dev libxrandr-dev libudev-dev mesa-common-dev libopengl-dev libflac-dev libogg-dev libvorbis-dev libopenal-dev libxcursor-dev"

jobs:
  build_game:
    resource_class: small
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run: apt-get update -q
      - run:
          name: Install dependencies
          command: apt-get install -q -y clang make cmake git <<pipeline.parameters.sfml_dependencies>>
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          command: mkdir -p build && cmake -B build -S . && cmake --build ./build
          name: Build the project
      - run:
          command: ./build/meat_boy-test
          name: Test parts of the project

workflows:
  build_game:
    jobs:
      - build_game
