name = "I didn't want this!"

[camera]
height = 10
increment = 0

[level]
map = '''
xxxxxxxxxxxxxxx
x             x
x  xxxxxx  xxxx
x  xg      x  x
x  xxxxxxxxx  x
x             x
xxxxxxx xxxxxxx
x             x
x             x
x     xxx     x
x     xxx     x
x    xxxxx    x
x             x
x   xx   xx   x
x xxxx   xxxx x
xxxxxx   xxxxxx
x             x
x             x
x             x
xx           xx
xxxx       xxxx
xxxxxxp  xxxxxx
xxxxxxxxxxxxxxx
'''
