name = "Jump!"

[camera]
height = 20
increment = 0

[level]
map = '''
xxxxxxxxxxxxxxx
x             x
x             x
x             x
x           g x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
x             x
xp            x
xxxxxxxxxxxxxxx
'''
